- scopeprotocols/CMakeLists.txt
- scopeprotocols/FFTDecoder.cpp
Right now a system ffts library is blindly used without regard to the found package.
> Actually use the results of FindFFTS

- scopeprotocols/CANDecoder.cpp
- scopeprotocols/CANDecoder.h
- scopeprotocols/CANRenderer.cpp
- scopeprotocols/CANRenderer.h
- scopeprotocols/CMakeLists.txt
- scopeprotocols/scopeprotocols.cpp
- scopeprotocols/scopeprotocols.h
This PR adds an incomplete CAN decoder, i.e.: standard frame ID only, no CRC verification, no transmission error check (partially implements #32)
Other than that, I think it works _pas mal_ at least in my tests. I didn't want to delay the PR.
I will continue to add improvements as I can.
Please let me know if I can make any modification.
> Add an incomplete CAN decoder

- scopehal/SiglentSCPIOscilloscope.cpp
For now, I've only enabled this fix for the SDS2000X, but all manuals indicate that dividing by 25 is required.
Also uses GetHwname() instead of the earlier clunky way of selecting the channel.
> Fix Siglent SDS2000X acquired data voltage calculation

- scopehal/SCPILxiTransport.cpp
This should fix https://github.com/azonenberg/scopehal-cmake/issues/12.
> Cast to non-const for interop with old liblxi.

- scopehal/CMakeLists.txt
- scopehal/LeCroyOscilloscope.cpp
- scopehal/LeCroyOscilloscope.h
- scopehal/RigolOscilloscope.cpp
- scopehal/SCPILxiTransport.cpp
- scopehal/SCPILxiTransport.h
- scopehal/SiglentSCPIOscilloscope.cpp
- scopehal/SiglentSCPIOscilloscope.h
- scopehal/scopehal.cpp
- scopeprotocols/CMakeLists.txt
- scopeprotocols/FFTDecoder.cpp
- scopeprotocols/SincInterpolationDecoder.cpp
This PR contains various fixes that allow scopehal and scopeprotocols to be compiled on Win32.
> Fixes to allow compilation on Win32

- scopehal/LeCroyOscilloscope.cpp
- scopehal/LeCroyOscilloscope.h
Replaced `localtime_r` with `localtime_s` when compiling for Windows.
> [WIP] Fixed LeCroy driver to work on Win32

- scopehal/CMakeLists.txt
- scopehal/scopehal.cpp
- Currently, the loader only searches in the `/plugins/` subdirectory of the folder the binary is located in. This is common for Windows software.
- Only files ending in `*.dll` are supported
> Implemented plugin loading for Win32

- scopehal/RigolOscilloscope.cpp
- scopehal/RigolOscilloscope.h
Also removed usleep as requested
> Add Trigger Offset to Rigol

- scopehal/SCPISocketTransport.cpp
It appears that setting a timeout before connecting just gets reset. So setting the timeout after connecting fixes the problem.
This fix depends on https://github.com/azonenberg/xptools/pull/12
> set rx/tx timeout after connect, to avoid it being reset

- scopeprotocols/CMakeLists.txt
- scopeprotocols/DeEmbedFilter.h
- scopeprotocols/FFTFilter.h
- scopeprotocols/OFDMDemodulator.h
From how FindFFTS.cmake works, LIBFFTS_INCLUDE_DIR will already
include the ffts/ component.
Fixes #230
Signed-off-by: Sylvain Munaut <tnt@246tNt.com>
> Fix ffts include path

- scopehal/scopehal.h
Add #define __USE_MINGW_ANSI_STDIO 1
Required for MSYS2 mingw64 to C *printf Format "%zu" ...
For more details see https://www.msys2.org/wiki/Porting chapter C *printf Format Specifier issues
> Add specific define for MSYS2 mingw64 to support C *printf Format %z

- scopehal/RigolOscilloscope.cpp
Fix the issue https://github.com/azonenberg/scopehal/issues/358 "glscopeclient hangs on Rigol MSO5000"
This fix Rigol MSO5000 oscilloscope single trigger synchronization with waveform data by adding "*WAI" command which "Waits for all the pending operations to complete before executing any additional commands." (it is an IEEE488.2 Common Commands)
> Fix glscopeclient hangs on Rigol MSO5000

- scopehal/RigolOscilloscope.cpp
Optimize Rigol MSO5000 AcquireData as it does not requires "WAV:STAR" "WAV:STOP" SCPI commands before to call "WAV:DATA?"
> Optimize Rigol MSO5000 AcquireData

- scopehal/scopehal.cpp
Compute next highest power of 2 to fix issues when using code (in different parts):
const size_t npoints = pow(2, ceil(log2(depth))); (see scopehal\TestWaveformSource.cpp => TestWaveformSource::DegradeSerialData()...)
The original code (pow(2, ceil(log2())) has some border effects when built with MSYS2 mingw64 "Release" mode as it does not compute correctly the highest power of 2 for example with parameter 100000 it was returning 131071 (instead of 131072) which crashed ffts.
This implementation fix issue https://github.com/azonenberg/scopehal-apps/issues/295
The function next_pow2() shall replace pow(2, ceil(log2())) in following code:
scopehal\TestWaveformSource.cpp
Line 282: 	//const size_t npoints = pow(2, ceil(log2(depth)));
scopeprotocols\DeEmbedFilter.cpp
Line 230: 	const size_t …
> Compute next highest power of 2 function

- scopehal/TestWaveformSource.cpp
Compute next highest power of 2 to fix issues when using code (in different parts):
const size_t npoints = pow(2, ceil(log2(depth))); (see scopehal\TestWaveformSource.cpp => TestWaveformSource::DegradeSerialData()...)
The original code (pow(2, ceil(log2())) has some border effects when built with MSYS2 mingw64 "Release" mode as it does not compute correctly the highest power of 2 for example with parameter 100000 it was returning 131071 (instead of 131072) which crashed ffts.
This implementation fix issue azonenberg/scopehal-apps#295
> Fix Demo (TestWaveformSource.cpp) crash issue with MSYS2 mingw64 Release build

- scopeprotocols/DeEmbedFilter.cpp
Compute next highest power of 2 to fix issues when using code (in different parts):
const size_t npoints = pow(2, ceil(log2(npoints_raw)));
The original code (pow(2, ceil(log2())) has some border effects when built with MSYS2 mingw64 "Release" mode as it does not compute correctly the highest power of 2 for example with parameter 100000 it was returning 131071 (instead of 131072) which crashed ffts.
This implementation fix issue azonenberg/scopehal-apps#295
> Fix DeEmbedFilter.cpp crash issue with MSYS2 mingw64 Release build

- scopeprotocols/FFTFilter.cpp
Compute next highest power of 2 to fix issues when using code:
const size_t npoints = pow(2, ceil(log2(npoints_raw)));
The original code (pow(2, ceil(log2())) has some border effects when built with MSYS2 mingw64 "Release" mode as it does not compute correctly the highest power of 2 for example with parameter 100000 it was returning 131071 (instead of 131072) which crashed ffts.
This implementation fix issue azonenberg/scopehal-apps#295
> Fix FFTFilter.cpp crash issue with MSYS2 mingw64 Release build

- scopeprotocols/CANDecoder.cpp
This should verify the checksum and resolve #333. Anything else you'd like to add? Are there tests I need to update?
> Verify CAN CRC (#333)

- scopehal/AgilentOscilloscope.cpp
Previously, this would be left at some smaller default value and the
scope would downsample the displayed points to hit that number.
Instead, request all available points (but the scope will only return
what is displayed).
> AgilentOscilloscope: request max points

- scopehal/MockOscilloscope.cpp
- scopehal/MockOscilloscope.h
- scopehal/scopehal.cpp
This PR adds a parser for Agilent, Keysight and Rigol multi-channel binary waveform capture files.
I've added helper functions `ReadFromFile()`, `BytesToInt()`, `BytesToFloat()` and `BytesToDouble()` to make parsing the file headers easier. I don't write C++ code all that often so let me know if there's a better way to do this.
See related PR azonenberg/scopehal-apps#307 for changes to Import dialog.
> Add binary capture file parser

- scopehal/LeCroyOscilloscope.cpp
- scopehal/LeCroyOscilloscope.h
- scopehal/OscilloscopeChannel.h
- scopehal/SCPISocketTransport.cpp
- scopehal/SCPISocketTransport.h
- scopehal/SCPITransport.cpp
- scopehal/SCPITransport.h
- scopehal/SiglentSCPIOscilloscope.cpp
- scopehal/SiglentSCPIOscilloscope.h
- scopehal/UartTrigger.cpp
- scopehal/UartTrigger.h
These changes provide minimal support for the SDS2000. Further testing and cleanup is still needed and this should be viewed as alpha level code.
> Changes to support SDS2000+ scope

- scopeprotocols/SWDDecoder.cpp
- scopeprotocols/SWDDecoder.h
Note that leaving dormant state is untested as I don't have anything that uses dormant state to hand at the moment.  
This patch fixes up line reset handling and protocol state changes (i.e. switching to/from SWD or Dormant state). It also adds parity checking on the send and receive packets and request headers.
> Add line resets, protocol switching and parity checking to SWD

- scopehal/RohdeSchwarzOscilloscope.cpp
- scopehal/RohdeSchwarzOscilloscope.h
This PR adds cache to the COUP query for RS scopes.
Additionally, on RTM3000, actual response is "DCL" or "ACL", added that condition also.
> Add cache to COUP on RS scopes, fix wrong COUP response

- scopehal/RohdeSchwarzOscilloscope.cpp
Sometimes scope would not reply to the HEAD query, or return 0 as length. If that's the case, querying for DATA would hang the scope.
This patch skips DATA query if HEAD response is invalid or zero.
Additionally, we were not checking if DATA was properly parsed, and we were alloc'ing based on garbage if there was a parse error.
> Avoid asking for data if not needed on RS driver

- scopehal/RohdeSchwarzOscilloscope.cpp
RTM3000 sends a LF after DATA. Read it so we don't get out of sync
> Read extra LF after DATA

- scopehal/SiglentSCPIOscilloscope.cpp
clang complains about std::string being used for variadic functions
> fix arguments to variadic functions to be c strings rather than std::string

- scopehal/scopehal.cpp
Temporary fix for FFT segfaults on Windows until https://github.com/azonenberg/scopehal-apps/issues/295 is researched more and/or resolved (might be compiler issue: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54412)
> Turn off AVX2 on Windows for now

- scopehal/DropoutTrigger.cpp
- scopehal/PulseWidthTrigger.cpp
- scopehal/RuntTrigger.cpp
- scopehal/SiglentSCPIOscilloscope.cpp
- scopehal/SiglentSCPIOscilloscope.h
- scopehal/SlewRateTrigger.cpp
Run through of all implemented triggering modes making sure they correspond to scope behaviours.
AFAIK they're all working fine now except RUNT triggers cannot set HLEVEL and LLEVELs...they both get the same value. Will send a bug request to Siglent.
There's no digital channels in here 'cos we still don't have the adapter yet.
As far as I'm concerned this can move from Alpha to Beta status now. It's functionally complete, but needs field test.
> Changes as a result of testing Siglent Triggering modes

- scopehal/scopehal.cpp
Guix installs each package to a seperate folder under `/gnu/store/<hash>-<packagename>-<version>` (similar to Nix / NixOS).
By default the produces a tree like this:
```
/gnu/store/pxgpg9kagg7gbs8dijgr40lvb7wicvhg-glscopeclient-0.0-0e57974d7
├── bin
│  └── glscopeclient
└── share
└── glscopeclient
├── gradients
│  └── [...]
├── icons
│  └── [...]
├── kernels
│  └── [...]
├── shaders
│  └── [...]
└── styles
└── [...]
```
So this adds the search paths necessary on such a platform.
> Add additional search paths used on Guix

- scopehal/SiglentSCPIOscilloscope.cpp
Test for enabled channels did not prevent channel data being requested, which put the protocol out of sequence. Empirically appears to restore speeds to those documented in the manual, but that will be verified tomorrow.
Also fixes memory depth setting.
> Fix channel pull request to match number of enabled channels

- scopehal/PicoOscilloscope.cpp
For some godforsaken reason, Windows insists that longs should be 32 bits wide, and Linux (I think) thinks they should be 64 bits wide. I'm currently running the picoscope SCPI bridge in a WSL instance, and glscopeclient on the Windows side. This is introducing crashes, as the picoscope bridge is happy to serialize a long > 32 bits max, but glscopeclient freaks out and crashes since this is above it's perceived max long value. Changing the SCPI parsing functions to use stoull should fix this, since all systems look like they agree that unsigned long long's are 64 bits wide.
> Change sample rate and depth conversions to use unsigned long longs

- scopehal/CMakeLists.txt
- scopehal/SCPILinuxGPIBTransport.cpp
- scopehal/SCPILinuxGPIBTransport.h
- scopehal/scopehal.cpp
- scopehal/scopehal.h
This adds support for using [linux-gpib](https://linux-gpib.sourceforge.io/) as SCPI transport. It'll be compiled in if `libgpib` can be found, similar to the current behaviour for LXI support.
I've tested with an Agilent 82357A USB/GPIB adapter and an MSO6034A using the `agilent` driver:
closes #574
> Add linux-gpib transport

- scopehal/AgilentOscilloscope.cpp
- scopehal/CMakeLists.txt
- scopehal/DCAEdgeTrigger.cpp
- scopehal/DCAEdgeTrigger.h
- scopehal/KeysightDCA.cpp
- scopehal/KeysightDCA.h
- scopehal/scopehal.cpp
This adds initial support for Keysight/Agilent/HP DCA line of equivalent-time sampling oscilloscopes.
It's been developed/tested on an Agilent 86100A and should work across the B/C/D variants of that line.
Plus a minor fix for the Agilent driver where I noticed it's sample-rate map wasn't private.
> Add Keysight DCA driver

- scopehal/CMakeLists.txt
Fix scopehal build for WIN32 (Windows mingw64)
To build successfully it is required to install VulkanSDK-1.3.224.1-Installer.exe and build glslang.git tags/sdk-1.3.224.1 with mingw64
- VulkanSDK-1.3.224.1-Installer.exe available on https://vulkan.lunarg.com/sdk/home
- Build glslang.git tags/sdk-1.3.224.1 with mingw64
```
cd ~
git clone https://github.com/KhronosGroup/glslang.git
cd glslang
git checkout tags/sdk-1.3.224.1
git clone https://github.com/google/googletest.git External/googletest
cd External/googletest
git checkout 0c400f67fcf305869c5fb113dd296eca266c9725
cd ../..
./update_glslang_sources.py
SOURCE_DIR=~/glslang
BUILD_DIR=$SOURCE_DIR/build
mkdir -p $BUILD_DIR
cd $BUILD_DIR
cmake -DCMAKE_BUILD_TYPE=Release -G"MinGW Makefiles" $SOURCE_DIR -DCMAKE_INSTALL_PREFIX="$(pwd)/install" …
```
> Fix scopehal build for WIN32 (Windows mingw64)

- scopeexports/CSVExportWizard.cpp
- scopehal/CMakeLists.txt
- scopehal/RemoteBridgeOscilloscope.cpp
- scopehal/VulkanInit.cpp
- scopehal/scopehal.cpp
These changes are sufficient to get scopehal compiling and working on my M1 Max MacBook Pro using clang-14 from homebrew.
The reworked Vulkan library includes _should_ be fine across multiple platforms when combined with a small change to the `scopehal-apps` CMakeList.txt that I'll be including in a separate PR in that repository:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -55,6 +55,7 @@ include(FindOpenMP)
find_package(glfw3 3.2 REQUIRED)
+set(Vulkan_FIND_COMPONENTS glslang shaderc_combined)
include(FindVulkan)
if(NOT Vulkan_FOUND)
```
I'm happy to find other means of making the macOS CMake setup happy if this causes issues on other platforms, though.
> macOS Compile Fixes

- scopehal/CMakeLists.txt
- scopehal/GWInstekGPDX303SPowerSupply.cpp
- scopehal/GWInstekGPDX303SPowerSupply.h
- scopehal/PowerSupply.cpp
- scopehal/PowerSupply.h
- scopehal/RohdeSchwarzHMC804xPowerSupply.cpp
- scopehal/RohdeSchwarzHMC804xPowerSupply.h
- scopehal/scopehal.cpp
This PR adds support for the basic features of the GW Instead GPD-X303S series power supplies, tested against a GPD-3303S with a macOS build of ngscopeclient. Several extensions were made to the PowerSupply.h interface to allow querying for features that distinguish these supplies from the existing R&S HMC804x power supplies that are supported.
Future work includes adding support for tracking series/parallel modes - as I started taking a look at the changes that would entail, it was going to take some more thought.
This is my first scopehal driver - let me know if there's anything that I can adjust to better fit in the existing codebase. I added some doxygen comments for the new power supply feature support query methods. There does not seem to be any documentation in `scopehal-docs` …
> Add basic support for GW Instek GPD-(X)303S power supplies

- scopehal/RigolOscilloscope.cpp
This PR fixes a crash with the Rigol MSO5000 where if waveform data was requested too quickly after a trigger event, the scope would send a response header but no waveform data to follow it. Additionally, there are some quality-of-life improvements/bugfixes.
> Rigol MSO5000 Fixes

- scopehal/ComputePipeline.cpp
MoltenVK seems to validate the descriptors pretty strictly and this was returning eErrorOutOfPoolMemory due to the lack of a provided pool of eStorageImage.
> Add missing pool size for eStorageImage descriptor

- scopehal/CMakeLists.txt
Precompiling these system/library headers takes a clean build of ngscopeclient from ~100-135s to ~40-45 seconds on my MacBook, a 60+% improvement.
Incremental rebuild speed is still suboptimal, since a change in pretty much any header file will cause every .cpp file to be recompiled. I may clean up an experimental branch that removes library-internal usage of `scopehal.h` and `scope protocols.h` to improve this situation as follow-up work.
> Precompile selected headers to improve compile times

- scopehal/CMakeLists.txt
YAML_INCLUDES is not available becase we're not using FindPackage for yaml-cpp on windows. Hard-code the path to the mingw64 package's includes dir for now.
> Hopefully fix windows build pre-compiled headers

- scopehal/CMakeLists.txt
The build still wasn't happy with my fix in #702 (https://github.com/glscopeclient/scopehal-apps/actions/runs/3169429026/jobs/5161334902), so tack on the rest of the path as well.
> Hardcode the windows yaml-cpp path even more.

- scopehal/avx_mathfun.h
Add AVX2 feature attributes to avx_mathfun header. This seems to be needed for clang to properly compile with the correct ABI. Without this change, clang requires the whole binary to be linked with -mavx to avoid error, presumably because the function's interface types change the ABI.
> Fix compile issues on x86_64 clang

- scopehal/CMakeLists.txt
- scopehal/Oscilloscope.cpp
- scopehal/SCPINullTransport.cpp
- scopehal/scopehal.cpp
- scopehal/scopehal.h
This PR cleans up all unconditional uses of POSIX APIs I found in the repository, and along with a small additional PR to follow in glscopeclient/scopehal-apps, will close https://github.com/glscopeclient/scopehal/issues/711.
> Remove usage of posix APIs

- scopehal/AgilentOscilloscope.cpp
This adds a missing `MarkSamplesModifiedFromCpu` call to the AgilentOscilloscope driver, that was preventing waveforms from being drawn.
I also made it use `ConvertUnsigned8BitSamples`, while I was making changes :)
> Fix waveform drawing for the AgilentOscilloscope driver

- scopehal/CMakeLists.txt
Fixes macOS build with latest libomp from brew.
> Explicitly add OpenMP include directory to build.

- scopehal/Filter.h
Fix the `SampleOnRisingEdgesBase` filter to sample on rising edges instead of any edge
Discovered and tested with RGMII analyzer
> Fix SampleOnRisingEdgesBase to use SampleOnRisingEdges

- scopeprotocols/USB2PacketDecoder.cpp
Previously, when looking for a response to a setup packet, DecodeSetup would consume the subsequent packet whether it was an ACK/NACK or not.
In cases where the device did not reply, the decoder would consume a packet from the next transaction and break the decoding.
This commit makes sure that DecodeSetup only consumes the subsequent packet iff it is an ACK or NAK.
fixes #723
> USB2PacketDecoder: fix DecodeSetup behaviour when the ACK/NAK packet is missing

- scopeprotocols/EthernetRMIIDecoder.cpp
Tested on a LA waveform from an MSO5074. Without preamble wait analysis hangs.
> RMII Decoder - wait for preamble before decoding for PHYs with leading CTL (LAN8270)

- scopeprotocols/BINImportFilter.cpp
In Agilent format .bin capture files generated by the Rigol MSO5000, logic analyzer data is stored as what Agilent refers to as "Counts 32-bit float data" buffer data format, which appears to be the 0-255 value encoded as a 32 bit float, instead of the format used by InfiniiVision scopes of 1 byte digital data.
example capture attached
[RigolDS8.bin.zip](https://github.com/glscopeclient/scopehal/files/10243556/RigolDS8.bin.zip)
> Add Rigol MSO5000 LA .bin support

- scopehal/SCPITMCTransport.cpp
- scopehal/SCPITMCTransport.h
- scopehal/SiglentSCPIOscilloscope.cpp
We can configure the USBTMC transfer size
for example: opening /dev/ubtmc0 with transfer size 48 /dev/usbtmc0:48
glscopeclient myscope:siglent:usbtmc:/dev/usbtmc0:48
Workaround for Siglent SDS1x04X-E. Max request size is 48 byte. Bug in firmware 8.2.6.1.37R9 ?
> Fix for #652

- scopehal/RSRTO6Oscilloscope.cpp
Replace usleep(..) by std::this_thread::sleep_for(std::chrono::microseconds(..)) to fix issue https://github.com/glscopeclient/scopehal/issues/765
> Replace usleep(..) by std::this_thread::sleep_for(std::chrono::microseconds(..)) to fix issue #765

- scopeprotocols/USB2PMADecoder.cpp
USB 2.0 - 7.1.7.2 - Table 7-3 states that "receiver must not indicate squelch if magnitude of differential voltage is ≥150 mV".
Also in the receiver sensitivity section, some of the eye templates show "must decode" eyes as low as 150 mW in some cases.
> USB2PMADecoder: Adjust high speed threshold level

- scopeprotocols/USB2PMADecoder.cpp
The threshold to use to see if we have a valid differential signals (DP - DN) is different from the one to use to see if we're in SE00 or SE11.
- For LS/FS USB 2.0 -  7.1.71 - Table 7-2 States that 200 mV differential is enough and that SE1 requires both lines to be above Vil
- For HS USB 2.0 - 7.1.7.2 - Table 7-3 States that 150 mV differential is enough
- USB 2.0 - 7.3.2 - Tables 7-7 Gives Vil = 0.8V
> USB2PMADecoder: Use different threshold for Differential and Single Ended

- scopehal/scopehal.cpp
Fix issue https://github.com/glscopeclient/scopehal-apps/issues/596
Potentially the same fix shall be done also for those API
https://github.com/glscopeclient/scopehal/blob/master/scopehal/scopehal.cpp
- ReadDataFile()
- ReadDataFileUint32()
To be discussed
> Update scopehal.cpp FindDataFile to use relative path when possible

- scopehal/QueueManager.cpp
Fixes https://github.com/glscopeclient/scopehal-apps/issues/597, where non-graphics queue would be selected for rendering.
This fixes the issue by requiring QueueManager check if the queue has all the requisite flags rather than some.
> Fix incorrect Vulkan queue type selection on some AMD GPUs

- scopehal/QueueManager.cpp
This corrects Vulkan queue sort order from descending to ascending order of feature flag count. This is the intended sort behavior as stated in the sort comment.
This addresses the side effect from descending order sort, where QueueManager assigns a more featureful queue even though a more appropriate queue with fewer features is available. This side effect manifests on AMD integrated GPUs by assigning the only graphics-capable queue to g_vkTransferQueue (which only require Transfer capability) and rendering tasks.
For reference, we want to prioritize queues with the fewest features and reserve more general-purpose queues (with graphics capabilities) for graphics/rendering tasks. This works on the assumption that graphics-capable queues support more features.
> Correct ascending sort of Vulkan queues by feature flag count

- scopehal/DigilentOscilloscope.cpp
`long` is not enough for femtoseconds
> Fixed overflow in Digilent RATES

- scopehal/RigolOscilloscope.cpp
Fixes bug where channel enable list will never be updated after initial states are polled
Tested on Rigol MSO5074 with v00.01.03.03.00 FW, with full unlocks
> Fix stale rigol channel enable states

- scopehal/SiglentSCPIOscilloscope.cpp
- scopehal/SiglentSCPIOscilloscope.h
Fixes #784.
Tasks:
- I currently assume data size bug is present in versions 1.3.9R6 and older.
> [Siglent SDS2000X Plus] Fix ADC mode setting; Fix slow 10-bit data acquisition with newer firmware

- scopehal/SiglentSCPIOscilloscope.cpp
This fixes attenuation value not being set on SDS2000X+/SDS2000XHD/SDS5000X/SDS6000 due to incorrect command syntax.
> SiglentSCPIOscilloscope: Fix attenuation set command syntax for SDS2000X+ and higher models

- scopehal/SiglentSCPIOscilloscope.cpp
This resolves #821 and addresses unexpected force trigger as a result of changing ADC mode while operating in normal mode (continuous single trigger). See #820 for reference on force trigger by setting single trigger mode.
> SiglentSCPIOscilloscope: improve SetADCMode reliability for SDS2000X+

- scopeprotocols/CurrentShuntFilter.cpp
This fixes segfault by correcting a typo and allocating space for output.
> CurrentShuntFilter: fix segfault when handling uniform analog input data

- scopehal/ScopehalUtil.cpp
- scopehal/StandardColors.h
Disabling PCH reveals these missing headers.
> Add missing includes masked by PCH

- scopehal/scopehal.cpp
On Windows, __builtin_clzl() only handles 32-bit inputs due to LLP64. This causes problems when larger values are used. Changing this to __builtin_clzll() fixes the crashes. This most notably fixes the crash when running the demo scope on Windows, as next_pow2() is used in the code that performs the downscaling using FFTS.
> Fix next_pow2 for LLP64 (Windows)

- scopehal/EyeWaveform.cpp
- scopehal/Filter.h
This currently causes an infinite loop and hang when mousing over eye charts on arm64.
> Fix undefined behavior due to casts from float to unsigned int

- scopehal/BERT.cpp
- scopehal/CDRTrigger.h
- scopehal/CSVStreamInstrument.cpp
- scopehal/EyeMask.cpp
- scopehal/Filter.h
- scopehal/FilterParameter.h
- scopehal/FlowGraphNode.h
- scopehal/FunctionGenerator.cpp
- scopehal/Load.cpp
- scopehal/MockOscilloscope.cpp
- scopehal/Multimeter.cpp
- scopehal/Oscilloscope.cpp
- scopehal/PowerSupply.cpp
- scopehal/RFSignalGenerator.cpp
- scopehal/SCPIInstrument.cpp
- scopehal/SCPISDR.cpp
- scopehal/SCPISpectrometer.cpp
- scopeprotocols/IBISDriverFilter.cpp
This adds support for the newer sigcxx and cairomm APIs. The old APIs still work.
> Support sigcxx 2 and 3 API, and cairomm 1 and 1.16 API

- scopehal/CMakeLists.txt
- scopeprotocols/CMakeLists.txt
This is a part of a heavy refactor of the Cmake scripts to increase the use of autodetection and reduce the reliance on `FindVulkan`, [which is going away in the future and is unreliable when the various components are installed individually](https://gitlab.kitware.com/cmake/cmake/-/issues/25617).
This requires the related PR for `scopehal-apps`, and is being tracked there at https://github.com/ngscopeclient/scopehal-apps/pull/673.
This is ready for merge; updates to the docs will be needed though.
> Refactor of Cmake scripts

- scopehal/Oscilloscope.cpp
Debian bookworm ships GCC 12.2, which throws this spurious warning. This is fixed in GCC 12.3.
> Fix AVX512 build on certain buggy compilers (e.g. GCC 12.2)

- scopehal/AcceleratorBuffer.h
- scopehal/VulkanInit.cpp
- scopehal/scopehal.h
Fixes #681. Tested on M2 MacBook Air. Will test on Intel integrated GPU to observe behavior (Intel GPU may have separately allocated VRAM, so may not utilize this optimization).
> Optimize AcceleratorBuffer for unified memory

- scopehal/AgilentOscilloscope.cpp
Without this the history dialog would only show one waveform, that would get overwritten on each trigger.
> AgilentOscilloscope: add missing timestamp for digital waveforms

- scopehal/SiglentSCPIOscilloscope.cpp
This warning trips up compile on recent versions of GCC (mainly GCC 14.1), which is current on recent versions of Fedora, Arch Linux, and Windows MSYS2.
> Work around likely GCC14 bug by disabling Werror for Warray-bounds in one location

- scopehal/SiglentSCPIOscilloscope.cpp
This PR fixes support for recent (2024) firmware updates that dropped support for undocumented `:TRIGGER:MODE STOP` command and changed version string format on SDS2000X+ models.
> Siglent: Replace :TRIG:MODE STOP with :TRIG:STOP; handle new SDS2000X+ version format

- scopehal/Oscilloscope.cpp
- scopehal/Oscilloscope.h
- scopehal/RigolOscilloscope.cpp
- scopehal/RigolOscilloscope.h
Hi Andrew,
As mentioned on Discord, I spent some time testing ngscopclient with my Rigol DHO804 (revamped in a DHO924).
This PR fixes some bugs encountered on large memory depth by activating pagination.
I also created a special "live" mode for memory depth =1k to take advantage of Rigol's "screen" mode.
This allows to double the frame rate at this memory depth.
Finally I tried to fix support for DHO1000/4000 (to be checked with someone owning this models).
Please let me know if it's OK for you to merge.
Oh and to prevent crashes due to the scope returning a null sample_per_rate value in rare cases, I forced it to a dummy value to prevent an Arithmetic exception in WaveformArea::RasterizeAnalogOrDigitalWaveform, but maybe it would be better to handle that in this method. 
Best,
Frederic.
> Rigol dho support enhancement

- scopehal/RigolOscilloscope.cpp
- scopehal/RigolOscilloscope.h
It's possible to ask DHO4000 what the capture time offset was with `:WAVeform:XORigin?`.  There is also `:WAVeform:XREFerence?` but [the manual (page 414)](https://tw.rigol.com/tw/Images/DHO10004000_ProgrammingGuide_EN_tcm17-5395.pdf) says it always returns 0.
While we are in there, it is not possible to know the bandwidth of a DHO4000 only by looking at its model number: you also have to look at the upgrade keys to see if the user has added the bandwidth option -- or if they have [downloaded more RAM](https://downloadmoreram.com/) with the memory depth unlock.  (We currently don't do anything with that, but we might as well make the member variables correct if we can!)
> RigolOscilloscope: add DHO4000 Xorigin support and bandwidth/memory option detection

- scopehal/base64.cpp
- scopehal/base64.h
signed/unsigned char is implementation-dependent.
This seems to break linux-aarch64 compilation ([build logs](https://logs.ofborg.org/?key=nixos/nixpkgs.336646&attempt_id=1a286230-ea8b-4714-8f7d-b4d3407463a4)).
Let's explicit `signed char` to fix aarch64 compilation.
Fix https://github.com/ngscopeclient/scopehal/issues/887.
> base64.cpp: explicit signed char

- scopehal/RigolOscilloscope.cpp
- scopehal/RigolOscilloscope.h
As requested by joshua_, here is the 16bit data transfert mode for Rigol DHO models.
Tested OK on my DHO804. Should work on DHO1000/4000 as well.
I used the same default/8bit/16bit setting system as for Siglent HD models.
Goes with the companion PR on scopehal-apps for settings.
> Rigol dho highres support

- scopehal/SiglentSCPIOscilloscope.cpp
Here are some enhancements for Siglent driver, including command rate limiting lowered to 5ms.
> Reduced command rate limiting for newer models + fixes.

- scopehal/DemoOscilloscope.cpp
- scopehal/Oscilloscope.cpp
- scopehal/Oscilloscope.h
- scopehal/RigolOscilloscope.cpp
- scopehal/SiglentSCPIOscilloscope.cpp
This fixes a bug in Siglent driver for progress of digital channels + removes calls to ChannelsDownloadStatusUpdate() with DOWNLOAD_NONE to prevent flickering.
> Fixes for download progress display.

- scopehal/CMakeLists.txt
- scopehal/KuaiquPowerSupply.cpp
- scopehal/KuaiquPowerSupply.h
- scopehal/ModbusInstrument.cpp
- scopehal/ModbusInstrument.h
- scopehal/RidenPowerSupply.cpp
- scopehal/RidenPowerSupply.h
- scopehal/scopehal.cpp
- scopehal/scopehal.h
Hi Andrew,
This PR adds support for Riden PSUs (tested with my RD6006, but should also work with other Riden PSUs).
Modbus protocol handling methods are sitting in the ModbusInstrument class (subclass of SCPIInstrument).
It's a first step for this feature request : https://github.com/ngscopeclient/scopehal-apps/issues/754
Best,
Frederic.
> Modbus + Riden RD and Kuaiqu SPPS PSUs support

- scopehal/ModbusInstrument.cpp
- scopehal/ModbusInstrument.h
Hi Andrew,
This is a small PR to end the job started with HID driver re. BinaryDriver helper class.
ModbusInstrument now uses BinaryDriver helper methods for push/read uint16 and CRC calculation.
Best,
Frederic.
> ModbusInstrument refactoring to use BinaryDriver helper methods

- scopehal/OwonXDGFunctionGenerator.cpp
- scopehal/OwonXDGFunctionGenerator.h
Hi Andrew,
This small PR just fixes copyright headers + some quirkynesses of XDG2035 on returned waveform shape names.
Best,
Frederic.
> Owon XDG driver fixes

- scopehal/CMakeLists.txt
- scopehal/SCPISA.cpp
- scopehal/SCPISA.h
- scopehal/SCPIUARTTransport.cpp
- scopehal/TinySA.cpp
- scopehal/TinySA.h
- scopehal/scopehal.cpp
- scopehal/scopehal.h
Hi Andrew,
This one adds a driver for the tinySA and tinySA ULTRA Spectrum Analyzers.
As these devices use UART over USB to communicate, I also added download progress support to SCPIUARTTransport class.
I also created a SCPISA base class that can be derived for other specan only instrument drivers.
Here is what it looks like:
It goes with a compagnon PR for documentation.
Best,
Frederic.
> tinySA and tinySA ULTRA driver

- scopehal/TektronixOscilloscope.cpp
- scopehal/TektronixOscilloscope.h
Hi Andrew,
To match the Specan fixes PR (https://github.com/ngscopeclient/scopehal-apps/pull/799), here is cache for frequency parameters on Tektronix driver, which was the only one not caching these values.
I could not test it since I don't have a Tek scope (I wish I did!;-), but hopefully I didn't break anything !...
Best,
Frederic.
> Tektronix driver - Cached frequency parameters

- scopehal/CMakeLists.txt
Newer versions of glslang do not ship this library separately, so we no longer need to link to it. Build works correctly on Windows and macOS.
> Fix Windows CI/build by removing no-longer-necessary link library
