scopehal/AgilentOscilloscope.cpp, scopehal/AgilentOscilloscope.h, scopehal/CMakeLists.txt
This is tested on an MSO6034A but should work on the 5000/7000 series too (initial dev happened on a 5014A but I don't have it anymore).
Should also work with the MSOX series with some minor patches from @tnt :)
=> Initial Agilent 5/6/7000 series support

scopehal/AgilentOscilloscope.cpp
Signed-off-by: Sylvain Munaut <tnt@246tNt.com>
=> scopehal/AgilentScope: Fix build warnings

scopehal/CMakeLists.txt, scopehal/SCPILxiTransport.cpp, scopehal/SCPILxiTransport.h, scopehal/scopehal.cpp, scopehal/scopehal.h
First stab at issue #118.
This can not be used as-is without changes that remove batching. 
Tom
=> Add SCPILxiTransport class.

scopehal/CMakeLists.txt, scopehal/SCPITMCTransport.cpp, scopehal/SCPITMCTransport.h, scopehal/scopehal.cpp
Usage:
```
./src/glscopeclient/glscopeclient myscope:siglent:usbtmc:/dev/usbtmc0
```
=> Support for USBTMC

scopeprotocols/USB2PCSDecoder.cpp, scopeprotocols/USB2PacketDecoder.cpp
A couple of little fixes I found while working on HS
=> USB decoder fixes

scopeprotocols/USB2PCSDecoder.cpp
=> USB2PCSDecoder: fix sync logic

scopehal/RigolOscilloscope.cpp
The data goes from 1-end apparently...
=> fixed rigol showing 'Invalid input'

scopehal/SiglentSCPIOscilloscope.cpp, scopehal/SiglentSCPIOscilloscope.h, scopehal/scopehal.cpp
This enables the last two drivers that were disabled on Win32.
=> Win32 reenable drivers

scopehal/CMakeLists.txt, scopehal/TektronixOscilloscope.cpp, scopehal/TektronixOscilloscope.h, scopehal/scopehal.cpp
This is very rudimentary code that can pull in waveforms from the scope, but that's about it.
The voltage calculation is still wrong. There are triggering issues that need to be worked out etc.
However, somebody showed interest in trying the code on his Tek scope, so I think it makes sense to add it to submit it.
Tom
=> Initial skeleton Tektronix support

scopehal/.clang-format, scopehal/RigolOscilloscope.cpp, scopehal/RigolOscilloscope.h
Improved rigol caching for attenuation, bandwidth and coupling
=> Rigol caching

scopehal/CMakeLists.txt, scopehal/SCPIUARTTransport.cpp, scopehal/SCPIUARTTransport.h, scopehal/scopehal.cpp
This depends on https://github.com/azonenberg/xptools/pull/13
=> add SCPIUARTTransport (fixes #159)

scopehal/RigolOscilloscope.cpp
works on revspace's DS1054Z with these two commits
=> misc Rigol fixes

scopehal/AgilentOscilloscope.cpp, scopehal/AgilentOscilloscope.h
This ticks off a bunch of items from #14, along with some general cleanup.
=> Agilent driver improvements

scopehal/AgilentOscilloscope.cpp, scopehal/AgilentOscilloscope.h
=> AgilentOscilloscope: support pulse width trigger

scopeprotocols/SWDDecoder.cpp
Simple fix to avoid dataphase and proceed direct to line turnover when an ACK status other than OK is detected.
=> When ACK!=OK there is no data phase

scopehal/SiglentSCPIOscilloscope.cpp
Schoolboy error. Fixed.  There's a collection of other things in the protocol still to be done, but this one makes the driver awkward to use...
=> Fix baseline offset setting

scopeprotocols/SWDDecoder.cpp
Tidy away warning about 'parity' not being set to initial value. Took opportunity to fix line reset and state change lengths for case where clock cycles are not the same length (it happens...)
=> Fix uninitialised variable warning and prettify SWD line reset ind.

scopehal/AgilentOscilloscope.cpp, scopehal/AgilentOscilloscope.h
=> Implement SetAttenuation for AgilentOscilloscope

scopehal/AgilentOscilloscope.cpp, scopehal/AgilentOscilloscope.h
=> AgilentOscilloscope: implement sample rate/depth API

scopehal/SiglentSCPIOscilloscope.cpp, scopehal/SiglentSCPIOscilloscope.h
Some tidying and work to make Siglent functional including preparing support for digital channels.
=> Fix trigger point calculations and improve off-channel handling

scopehal/SiglentSCPIOscilloscope.cpp
Some tidying and work to make Siglent functional including preparing support for digital channels.
=> Fix windows compilation error due to lack of usleep

scopehal/SiglentSCPIOscilloscope.cpp
Update following feedback from Siglent engineering, plus small fix to waveform offsets.
=> Fix digital levels and waveform offset

.gitmodules, scopehal/CMakeLists.txt, scopehal/PeakDetectionFilter.cpp, scopehal/scopehal.h
=> fix #474 (BSD build support)

scopehal/SiglentSCPIOscilloscope.cpp, scopehal/SiglentSCPIOscilloscope.h
I'm not overly happy about this because of limitations of the Siglent protocol (or my understanding of it). Requests have been made to Siglent for clarification, but for now this works _unless_ you've got very long acquisition times.
DAVE.
=> Addition of forced trigger

scopehal/CMakeLists.txt, scopehal/Unit.cpp, scopehal/scopehal.cpp
Fix windows/mingw build issues identified in  #502  
Also fix resource search path issues identified during testing. 
Should also pull matching PR in scopehal-apps and update the submodule.
=> Windows fixes

scopehal/RigolOscilloscope.cpp, scopehal/RigolOscilloscope.h
Improved the options readout of the Rigol oscilloscope, that it can get its actual capabilities and available bandwidth limiters.
=> Rigol improved options readout

scopehal/AgilentOscilloscope.cpp, scopehal/AgilentOscilloscope.h
=> AgilentOscilloscope: add support for digital channels

scopehal/MockOscilloscope.cpp, scopehal/Oscilloscope.cpp
Some minor issues that came up when trying to build on macOS.
=> Small Darwin build fixes

scopehal/SiglentSCPIOscilloscope.cpp
X (time) axis trigger position was not correct on Siglent SDS2000X+. This fixes the issue. Tested against firmware version 1.3.9R6.
=> Fix time axis offset inversion

scopehal/SiglentSCPIOscilloscope.cpp
...fix to upper and lower limit setting on Runt triggers.
=> Runt trigger upper and lower limit reversal fix

scopehal/SiglentSCPIOscilloscope.cpp
Fix SetChannelCoupling for MODEL_SIGLENT_SDS1000
Fix SetChannelOffset   for MODEL_SIGLENT_SDS1000
@mubes  can you please check. Thanks Stefan
=> Fix SetChannelCoupling for MODEL_SIGLENT_SDS1000

scopehal/SiglentSCPIOscilloscope.cpp
@ mubes  can you please check. Thanks Stefan
=> Fix SetChannelDisplayName 

scopehal/TektronixOscilloscope.cpp
Some minimum initial changes that allow connecting to a MSO5, and fixes for some parameter options for the MSO5.
=> Get driver running on MSO5

scopehal/SCPIDevice.cpp, scopehal/SCPISocketTransport.cpp, scopehal/TektronixOscilloscope.cpp, scopehal/TektronixOscilloscope.h
Fixes various crashes and lockups. Memory depth up to 125Mpts is supported now. Digital channels use RLE.
=> Tektronix MSO stability patches

scopehal/PicoOscilloscope.cpp
I somehow missed a semicolon T.T
=> Fix missing semicolon

scopehal/SCPILinuxGPIBTransport.cpp
Just a couple of minor fixes I found while working on the Keysight DCA driver
=> GPIB fixes

scopeprotocols/shaders/CMakeLists.txt
glscopeclient won't start if it can't load these shader files
=> install the compiled .spv filter files into share/glscopeclient/shaders

scopeprotocols/shaders/CMakeLists.txt
Fix issue https://github.com/glscopeclient/scopehal-apps/issues/470
=> Fix Compile shader using ${Vulkan_GLSLC_EXECUTABLE}

scopehal/Filter.cpp, scopehal/Filter.h, scopehal/Oscilloscope.cpp, scopehal/Oscilloscope.h, scopehal/PeakDetectionFilter.cpp, scopehal/TektronixOscilloscope.cpp, scopehal/avx_mathfun.cpp, scopehal/avx_mathfun.h, scopehal/scopehal.cpp, scopehal/scopehal.h, scopeprotocols/DeEmbedFilter.cpp, scopeprotocols/DeEmbedFilter.h, scopeprotocols/DownconvertFilter.cpp, scopeprotocols/DownconvertFilter.h, scopeprotocols/EyePattern.cpp, scopeprotocols/EyePattern.h, scopeprotocols/FFTFilter.cpp, scopeprotocols/FFTFilter.h, scopeprotocols/FIRFilter.cpp, scopeprotocols/FIRFilter.h, scopeprotocols/GroupDelayFilter.cpp, scopeprotocols/JitterSpectrumFilter.cpp, scopeprotocols/NoiseFilter.cpp, scopeprotocols/NoiseFilter.h, scopeprotocols/SpectrogramFilter.cpp, scopeprotocols/SpectrogramFilter.h, scopeprotocols/SubtractFilter.cpp, scopeprotocols/SubtractFilter.h, scopeprotocols/TappedDelayLineFilter.cpp, scopeprotocols/TappedDelayLineFilter.h
=> Add #ifdefs around x86-specific code.

scopeprotocols/BurstWidthMeasurement.cpp, scopeprotocols/BurstWidthMeasurement.h, scopeprotocols/CMakeLists.txt, scopeprotocols/scopeprotocols.cpp, scopeprotocols/scopeprotocols.h
This PR adds a Burst Width Measurement Filter.
=> Adding burst width measurement filter

scopeprotocols/CMakeLists.txt, scopeprotocols/TimeOutsideLevelMeasurement.cpp, scopeprotocols/TimeOutsideLevelMeasurement.h, scopeprotocols/scopeprotocols.cpp, scopeprotocols/scopeprotocols.h
=> Implemented Time outside level filter

scopehal/CMakeLists.txt, scopehal/Waveform.cpp, scopehal/Waveform.h, scopeprotocols/WindowFilter.cpp
Merge with https://github.com/glscopeclient/scopehal-apps/pull/530
=> Centralized helpers for getting indecies and values from waveform

scopehal/QueueManager.cpp
Chooses the queue with the fewest feature flags and fewest existing handles first.
=> Make Vulkan queue allocation pickier.

scopehal/TektronixOscilloscope.cpp
Fixes scope forgetting which channels were enabled after File->Default Setup.
Also fixes spurious digital channels being displayed on channels without a digital pod connected.
=> Fix bugs causing Tektronix driver to enable too many channels

scopehal/Filter.cpp, scopehal/Filter.h, scopehal/FlowGraphNode.cpp, scopehal/FlowGraphNode.h, scopehal/Oscilloscope.cpp, scopehal/Oscilloscope.h, scopehal/Trigger.cpp, scopehal/Trigger.h
Resolves glscopeclient/scopehal-apps#566
=> Use yaml-cpp for serialization instead of string concatenation

scopeprotocols/CMakeLists.txt, scopeprotocols/GlitchRemovalFilter.cpp, scopeprotocols/GlitchRemovalFilter.h, scopeprotocols/scopeprotocols.cpp, scopeprotocols/scopeprotocols.h
Removes samples shorter than a configurable value.
=> Add Glitch Removal Filter

scopeprotocols/CMakeLists.txt, scopeprotocols/SNRFilter.cpp, scopeprotocols/SNRFilter.h, scopeprotocols/scopeprotocols.cpp, scopeprotocols/scopeprotocols.h
Simple whole-waveform average/stddev SNR filter. Scalar output filter now that those have arrived :).
=> SNR Filter

scopehal/CMakeLists.txt, scopehal/RigolDP8xxPowerSupply.cpp, scopehal/RigolDP8xxPowerSupply.h, scopehal/scopehal.cpp
=> Support Rigol DP8xx PSUs

scopehal/CMakeLists.txt, scopehal/DemoPowerSupply.cpp, scopehal/DemoPowerSupply.h, scopehal/GWInstekGPDX303SPowerSupply.cpp, scopehal/PowerSupplyChannel.cpp, scopehal/PowerSupplyChannel.h, scopehal/RohdeSchwarzHMC804xPowerSupply.cpp, scopehal/scopehal.cpp
Depends on #774 (could be merged separate; just developed together.)
Needs docs.
=> Add DemoPowerSupply driver

scopehal/SiglentSCPIOscilloscope.cpp
SiglentSCPIOscilloscope implement SDS5000X specific sample rate and sample depth
Tested on SDS5104X
=> SiglentSCPIOscilloscope implement SDS5000X specific sample rate and sample depth

scopehal/Unit.h
This adds some additional missing includes for locale_t
=> Add missing includes masked by PCH (locale_t)

scopehal/Unit.cpp
Fix missing <cinttypes> include
=> Add missing include

scopehal/CMakeLists.txt, scopehal/HP662xAPowerSupply.cpp, scopehal/HP662xAPowerSupply.h, scopehal/scopehal.cpp
Add driver for my lovely boat anchor
=> Add driver for HP 662xA power supplies

scopehal/SiglentSCPIOscilloscope.cpp
Add switch case for more sds1000 trigger. 
Can someone with a Siglent SDS2000 test this ?
Hopefully it still works.
=> Add PullPulseWidthTrigger for siglent sds1000

scopehal/RigolOscilloscope.cpp, scopehal/RigolOscilloscope.h
- added additional protocol_version in "RigolOscilloscope.h" 
- reworked device detection and removed nested if's
- formatting
=> Added support for DHO800/DHO900 series

scopehal/RigolOscilloscope.cpp, scopehal/RigolOscilloscope.h
Hi Andrew,
This PR fixes Timebase settings for DHO models.
It's been tested on my DHO900.
Further testing is needed for DHO1000/4000 models (and maybe adjustments in samplerate value list).
Best,
Frederic.
=> Dho support fixes

scopehal/SiglentSCPIOscilloscope.cpp, scopehal/SiglentSCPIOscilloscope.h
Needs more consideration around memory depth and sample rates, which vary with model bandwidth and 1/2/4 channel selection..
=> Initial support for Siglent SDS800X HD

scopehal/ThunderScopeOscilloscope.cpp
Set and receive rates in Hz for the Thunderscope.
=> Thunderscope Rates in Hz

scopehal/ThunderScopeOscilloscope.cpp
Fix DC coupling commands to actually request DC coupling.
=> Fix TS coupling SCPI commands

scopehal/CMakeLists.txt, scopehal/OwonXDGFunctionGenerator.cpp, scopehal/OwonXDGFunctionGenerator.h, scopehal/scopehal.cpp
Hi Andrew,
This PR adds support for Owon XDG Function Generator series:
Best,
Frederic.
=> Owon xdg support

scopehal/AlientekPowerSupply.cpp, scopehal/AlientekPowerSupply.h, scopehal/CMakeLists.txt, scopehal/HIDInstrument.cpp, scopehal/HIDInstrument.h, scopehal/SCPIHIDTransport.cpp, scopehal/SCPIHIDTransport.h, scopehal/SCPIUARTTransport.cpp, scopehal/scopehal.cpp, scopehal/scopehal.h
Hi Andrew,
2/4 PR for hid transport support + Alientek DP100 driver.
This adds SCPIHIDTransport class + SCPIHIDInstrument.
Some refactoring will be needed after the merge of Modbus PR to create a common helper class for "BinaryDrivers" to implement common helper methods like PushUint16 and CRC calculation.
Best,
Frederic.
=> Hid transport support

scopehal/AlientekPowerSupply.cpp, scopehal/AlientekPowerSupply.h, scopehal/BinaryDriver.cpp, scopehal/BinaryDriver.h, scopehal/CMakeLists.txt, scopehal/HIDInstrument.cpp, scopehal/scopehal.h
Hi Andrew,
As you suggested on discord, I changed the prototypes of methods to make it clearer when vector parameters will not be modified.
I also refactored helper methods used to manipulate binary data in a dedicated BinaryDriver class that will be useful for https://github.com/ngscopeclient/scopehal/pull/902 too.
Best,
Frederic.
=> Binary driver helpers

scopehal/CMakeLists.txt, scopehal/OwonXDMMultimeter.cpp, scopehal/OwonXDMMultimeter.h, scopehal/scopehal.cpp
Hi Andrew,
A small one to add support for Owon XDM 1000 and 2000 meter series support.
A create for the doc update comes with it.
Best,
Frederic.
=> Driver for Owon XDM meters.

scopehal/CMakeLists.txt, scopehal/CommandLineDriver.cpp, scopehal/CommandLineDriver.h, scopehal/NanoVNA.cpp, scopehal/NanoVNA.h, scopehal/SCPIUARTTransport.cpp, scopehal/SCPIUARTTransport.h, scopehal/TinySA.cpp, scopehal/TinySA.h, scopehal/scopehal.cpp, scopehal/scopehal.h
Hi Andrew,
Here is a PR for the NanoVNA driver:
It uses the same kind of command line protocol as the TinySA for communication, so I created a CommandLineDriver class to factorize the common code.
This PR also comes with the addition of DTR flag to SCPIUARTTransport (that goes with https://github.com/ngscopeclient/xptools/pull/33 ).
Best,
Frederic.
=> Nanovna driver

scopehal/PicoOscilloscope.cpp
Same thing as in ngscopeclient/scopehal-pico-bridge#26
=> Fix issue with non MSO scopes

scopehal/shaders/RectangularWindow.glsl, scopeprotocols/AddFilter.cpp, scopeprotocols/FFTFilter.cpp, scopeprotocols/SubtractFilter.cpp, scopeprotocols/shaders/AddFilter.glsl, scopeprotocols/shaders/BlackmanHarrisWindow.glsl, scopeprotocols/shaders/ComplexRectangularWindow.glsl, scopeprotocols/shaders/ComplexToLogMagnitude.glsl, scopeprotocols/shaders/ComplexToMagnitude.glsl, scopeprotocols/shaders/CosineSumWindow.glsl, scopeprotocols/shaders/SubtractFilter.glsl
=> 64k shader refactor (#716)

scopehal/HaasoscopePro.cpp, scopehal/HaasoscopePro.h
Address https://github.com/ngscopeclient/scopehal/issues/999
=> Add GetSampleRate() SetSampleRate() GetSampleDepth() SetSampleDepth()
